insert into pzn  (id, abbreviation, name) values  ('00', 'ÃÓ/Î', 'Ãëàâíîå óïğàâëåíèå/Îòäåëåíèå (ÍÁ)');
insert into pzn  (id, abbreviation, name) values  ('10', 'ĞÊÖ', 'Ğàñ÷åòíî-êàññîâûé öåíòğ');
insert into pzn  (id, abbreviation, name) values  ('20', 'Á', 'Áàíê');
insert into pzn  (id, abbreviation, name) values  ('21', 'ÊÁ', 'Êîììåğ÷åñêèé áàíê');
insert into pzn  (id, abbreviation, name) values  ('22', 'ÑÁ', 'Ñáåğáàíê Ğîññèè');
insert into pzn  (id, abbreviation, name) values  ('23', 'ÀÊÁ', 'Àêöèîíåğíûé êîììåğ÷åñêèé áàíê');
insert into pzn  (id, abbreviation, name) values  ('24', '×ÊÁ', '×àñòíûé êîììåğ÷åñêèé áàíê');
insert into pzn  (id, abbreviation, name) values  ('25', 'ÊÎÏÁ', 'Êîîïåğàòèâíûé áàíê');
insert into pzn  (id, abbreviation, name) values  ('26', 'ÀÏÁ', 'ÀÊÁ \"ÀãğîÏğîìÁàíê\" è åãî ğåãèîí.ôèëèàëû');
insert into pzn  (id, abbreviation, name) values  ('30', 'ÔÁ', 'Ôèëèàë áàíêà');
insert into pzn  (id, abbreviation, name) values  ('31', 'ÔÊÁ', 'Ôèëèàë êîììåğ÷åñêîãî áàíêà');
insert into pzn  (id, abbreviation, name) values  ('32', 'ÔÑÁ', 'Ôèëèàë Ñáåğáàíêà');
insert into pzn  (id, abbreviation, name) values  ('33', 'ÔÀÊÁ', 'Ôèëèàë àêöèîíåğíîãî êîììåğ÷åñêîãî áàíêà');
insert into pzn  (id, abbreviation, name) values  ('34', 'Ô×ÊÁ', 'Ôèëèàë ÷àñòíîãî êîììåğ÷åñêîãî áàíêà');
insert into pzn  (id, abbreviation, name) values  ('35', 'ÔÊÎÁ', 'Ôèëèàë êîîïåğàòèâíîãî áàíêà');
insert into pzn  (id, abbreviation, name) values  ('36', 'Îòä.', 'Îòäåëåíèå \"ÀãğîÏğîìÁàíêà\"');
insert into pzn  (id, abbreviation, name) values  ('40', 'ÏÓ', 'Ïîëåâîå ó÷ğåæäåíèå Áàíêà Ğîññèè');
insert into pzn  (id, abbreviation, name) values  ('50', 'ÌĞÕ', 'Ìåæğåãèîíàëüíîå õğàíèëèùå');
insert into pzn  (id, abbreviation, name) values  ('70', 'ÍÊÎ', 'ÍÊÎ (ğàñ÷åòíûå,îğã-öèè èíêàññàöèè è äğ.)');
insert into pzn  (id, abbreviation, name) values  ('71', 'ÊË', 'Êëèğèíãîâîå ó÷ğåæäåíèå');
insert into pzn  (id, abbreviation, name) values  ('72', 'ÎĞÖÁ', 'Ğàñ÷åòíûé öåíòğ ÎĞÖÁ');
insert into pzn  (id, abbreviation, name) values  ('98', 'ÈÑÊË', 'Íà÷àò ïğîöåññ ëèêâèäàöèè');
insert into pzn  (id, abbreviation, name) values  ('99', 'ÎÒÇÂ', 'Îãğ.ğàñõ.îïåğ. ïî ïğèêàçó îá îòç.ëèöåíç.');
insert into pzn  (id, abbreviation, name) values  ('', '', 'Ïğèçíàê òèïà íå îïğåäåëåí');
insert into pzn  (id, abbreviation, name) values  ('**', '', 'Ïîäğ. Áàíêà Ğîññèè,íå îáñëóæèâ. êëèåíòîâ');
insert into pzn  (id, abbreviation, name) values  ('90', 'ËÈÊÂ', 'Ëèêâèäàöèîííàÿ êîìèññèÿ (ëèêâèäàòîğ)');
insert into pzn  (id, abbreviation, name) values  ('37', 'ÒÓÑÁ', 'Òåğğèòîğèàëüíûå óïğàâëåíèÿ Ñáåğáàíêà');
insert into pzn  (id, abbreviation, name) values  ('73', 'ÍÄÊÎ', 'ÍÊÎ, îñóù. äåïîçèòíî-êğåäèòíûå îïåğàöèè');
insert into pzn  (id, abbreviation, name) values  ('74', 'ÔÍÊÎ', 'Ôèëèàë ÍÊÎ');
insert into pzn  (id, abbreviation, name) values  ('91', 'ÊÓÏĞ', 'Êîíêóğñíûé óïğàâëÿşùèé');
insert into pzn  (id, abbreviation, name) values  ('75', 'ÔÄÊÎ', 'Ôèëèàë ÍÄÊÎ');
insert into pzn  (id, abbreviation, name) values  ('76', 'ÔĞÏ', 'Ôèëèàë ğàñ÷åòíîãî öåíòğà ÎĞÖÁ');
insert into pzn  (id, abbreviation, name) values  ('80', 'ÎÍÊ', 'Îğãàíèçàöèÿ, íå ÿâëÿşùàÿñÿ êğåäèòíîé');
insert into pzn  (id, abbreviation, name) values  ('11', 'ÏĞÑ', 'Ïîäğàçäåëåíèå ğàñ÷åòí. ñåòè Áàíêà Ğîññèè');
insert into pzn  (id, abbreviation, name) values  ('12', 'ÎÍÁ', 'Îòäåëåíèå (ÍÁ), íå âåäóùåå áàëàíñ');


insert into uer  (id, name) values  ('0', 'ÍÅ Ó×ÀÑÒÂÓÅÒ');
insert into uer  (id, name) values  ('1', 'ÒÎËÜÊÎ ÌÅÆĞÅÃÈÎÍÀËÜÍÛÅ ĞÀÑ×ÅÒÛ');
insert into uer  (id, name) values  ('2', 'ÒÎËÜÊÎ ÂÍÓÒĞÈĞÅÃÈÎÍÀËÜÍÛÅ ĞÀÑ×ÅÒÛ');
insert into uer  (id, name) values  ('3', 'ÌÅÆĞÅÃÈÎÍÀËÜÍÛÅ È ÂÍÓÒĞÈĞÅÃÈÎÍÀËÜÍÛÅ ĞÀÑ×ÅÒÛ');
insert into uer  (id, name) values  ('7', 'ÈÑÊËŞ×ÅÍ ÈÇ ÌİĞ, ÍÎ ĞÀÁÎÒÀÅÒ ÏÎ ÏÎÄÒÂÅĞÆÄÅÍÈßÌ ÌİĞ, Ó×ÀÑÒÍÈÊ ÂİĞ');
insert into uer  (id, name) values  ('4', 'Ó×ÀÑÒÍÈÊ ÌİĞ, ÂİĞ È ÎÑÎÁÛÉ Ó×ÀÑÒÍÈÊ ĞÀÑ×ÅÒÎÂ ÑÈÑÒÅÌÛ ÁİÑÏ');
insert into uer  (id, name) values  ('5', 'ÀÑÑÎÖÈÈĞÎÂÀÍÍÛÉ Ó×ÀÑÒÍÈÊ ÁİÑÏ È Ó×ÀÑÒÍÈÊ ÂİĞ');
insert into uer  (id, name) values  ('6', 'ÀÑÑÎÖÈÈĞÎÂÀÍÍÛÉ Ó×ÀÑÒÍÈÊ ÁİÑÏ È ÍÅ Ó×ÀÑÒÍÈÊ ÂİĞ');


insert into tnp  (id, name, short_name) values  ('1', 'ÃÎĞÎÄ', 'Ã');
insert into tnp  (id, name, short_name) values  ('2', 'ÏÎÑÅËÎÊ', 'Ï');
insert into tnp  (id, name, short_name) values  ('3', 'ÑÅËÎ', 'Ñ');
insert into tnp  (id, name, short_name) values  ('4', 'ÏÎÑÅËÎÊ ÃÎĞÎÄÑÊÎÃÎ ÒÈÏÀ', 'ÏÃÒ');
insert into tnp  (id, name, short_name) values  ('5', 'ÑÒÀÍÈÖÀ', 'ÑÒ-ÖÀ');
insert into tnp  (id, name, short_name) values  ('6', 'ÀÓË', 'ÀÓË');
insert into tnp  (id, name, short_name) values  ('7', 'ĞÀÁÎ×ÈÉ ÏÎÑÅËÎÊ', 'ĞÏ');


insert into reg  (id, name) values  ('00', 'ÒÅĞĞÈÒÎĞÈß ÍÅ ÎÏĞÅÄÅËÅÍÀ');
insert into reg  (id, name) values  ('01', 'ÀËÒÀÉÑÊÈÉ ÊĞÀÉ');
insert into reg  (id, name) values  ('03', 'ÊĞÀÑÍÎÄÀĞÑÊÈÉ ÊĞÀÉ');
insert into reg  (id, name) values  ('04', 'ÊĞÀÑÍÎßĞÑÊÈÉ ÊĞÀÉ');
insert into reg  (id, name) values  ('05', 'ÏĞÈÌÎĞÑÊÈÉ ÊĞÀÉ');
insert into reg  (id, name) values  ('07', 'ÑÒÀÂĞÎÏÎËÜÑÊÈÉ ÊĞÀÉ');
insert into reg  (id, name) values  ('08', 'ÕÀÁÀĞÎÂÑÊÈÉ ÊĞÀÉ');
insert into reg  (id, name) values  ('10', 'ÀÌÓĞÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('11', 'ÀĞÕÀÍÃÅËÜÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('12', 'ÀÑÒĞÀÕÀÍÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('14', 'ÁÅËÃÎĞÎÄÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('15', 'ÁĞßÍÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('17', 'ÂËÀÄÈÌÈĞÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('18', 'ÂÎËÃÎÃĞÀÄÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('19', 'ÂÎËÎÃÎÄÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('20', 'ÂÎĞÎÍÅÆÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('22', 'ÍÈÆÅÃÎĞÎÄÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('24', 'ÈÂÀÍÎÂÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('25', 'ÈĞÊÓÒÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('26', 'ĞÅÑÏÓÁËÈÊÀ ÈÍÃÓØÅÒÈß');
insert into reg  (id, name) values  ('27', 'ÊÀËÈÍÈÍÃĞÀÄÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('28', 'ÒÂÅĞÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('29', 'ÊÀËÓÆÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('30', 'ÊÀÌ×ÀÒÑÊÈÉ ÊĞÀÉ');
insert into reg  (id, name) values  ('32', 'ÊÅÌÅĞÎÂÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('33', 'ÊÈĞÎÂÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('34', 'ÊÎÑÒĞÎÌÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('36', 'ÑÀÌÀĞÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('37', 'ÊÓĞÃÀÍÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('38', 'ÊÓĞÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('40', 'Ã ÑÀÍÊÒ-ÏÅÒÅĞÁÓĞÃ');
insert into reg  (id, name) values  ('41', 'ËÅÍÈÍÃĞÀÄÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('42', 'ËÈÏÅÖÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('44', 'ÌÀÃÀÄÀÍÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('45', 'Ã ÌÎÑÊÂÀ');
insert into reg  (id, name) values  ('46', 'ÌÎÑÊÎÂÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('47', 'ÌÓĞÌÀÍÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('49', 'ÍÎÂÃÎĞÎÄÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('50', 'ÍÎÂÎÑÈÁÈĞÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('52', 'ÎÌÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('53', 'ÎĞÅÍÁÓĞÃÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('54', 'ÎĞËÎÂÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('56', 'ÏÅÍÇÅÍÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('57', 'ÏÅĞÌÑÊÈÉ ÊĞÀÉ');
insert into reg  (id, name) values  ('58', 'ÏÑÊÎÂÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('60', 'ĞÎÑÒÎÂÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('61', 'ĞßÇÀÍÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('63', 'ÑÀĞÀÒÎÂÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('64', 'ÑÀÕÀËÈÍÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('65', 'ÑÂÅĞÄËÎÂÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('66', 'ÑÌÎËÅÍÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('68', 'ÒÀÌÁÎÂÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('69', 'ÒÎÌÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('70', 'ÒÓËÜÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('71', 'ÒŞÌÅÍÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('73', 'ÓËÜßÍÎÂÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('75', '×ÅËßÁÈÍÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('76', 'ÇÀÁÀÉÊÀËÜÑÊÈÉ ÊĞÀÉ');
insert into reg  (id, name) values  ('77', '×ÓÊÎÒÑÊÈÉ ÀÎ');
insert into reg  (id, name) values  ('78', 'ßĞÎÑËÀÂÑÊÀß ÎÁËÀÑÒÜ');
insert into reg  (id, name) values  ('79', 'ĞÅÑÏÓÁËÈÊÀ ÀÄÛÃÅß');
insert into reg  (id, name) values  ('80', 'ĞÅÑÏÓÁËÈÊÀ ÁÀØÊÎĞÒÎÑÒÀÍ');
insert into reg  (id, name) values  ('81', 'ĞÅÑÏÓÁËÈÊÀ ÁÓĞßÒÈß');
insert into reg  (id, name) values  ('82', 'ĞÅÑÏÓÁËÈÊÀ ÄÀÃÅÑÒÀÍ');
insert into reg  (id, name) values  ('83', 'ÊÀÁÀĞÄÈÍÎ-ÁÀËÊÀĞÑÊÀß ĞÅÑÏÓÁËÈÊÀ');
insert into reg  (id, name) values  ('84', 'ĞÅÑÏÓÁËÈÊÀ ÀËÒÀÉ');
insert into reg  (id, name) values  ('85', 'ĞÅÑÏÓÁËÈÊÀ ÊÀËÌÛÊÈß');
insert into reg  (id, name) values  ('86', 'ĞÅÑÏÓÁËÈÊÀ ÊÀĞÅËÈß');
insert into reg  (id, name) values  ('87', 'ĞÅÑÏÓÁËÈÊÀ ÊÎÌÈ');
insert into reg  (id, name) values  ('88', 'ĞÅÑÏÓÁËÈÊÀ ÌÀĞÈÉ İË');
insert into reg  (id, name) values  ('89', 'ĞÅÑÏÓÁËÈÊÀ ÌÎĞÄÎÂÈß');
insert into reg  (id, name) values  ('90', 'ĞÅÑÏÓÁËÈÊÀ ÑÅÂÅĞÍÀß ÎÑÅÒÈß-ÀËÀÍÈß');
insert into reg  (id, name) values  ('91', 'ÊÀĞÀ×ÀÅÂÎ-×ÅĞÊÅÑÑÊÀß ĞÅÑÏÓÁËÈÊÀ');
insert into reg  (id, name) values  ('92', 'ĞÅÑÏÓÁËÈÊÀ ÒÀÒÀĞÑÒÀÍ');
insert into reg  (id, name) values  ('93', 'ĞÅÑÏÓÁËÈÊÀ ÒÛÂÀ');
insert into reg  (id, name) values  ('94', 'ÓÄÌÓĞÒÑÊÀß ĞÅÑÏÓÁËÈÊÀ');
insert into reg  (id, name) values  ('95', 'ĞÅÑÏÓÁËÈÊÀ ÕÀÊÀÑÈß');
insert into reg  (id, name) values  ('96', '×Å×ÅÍÑÊÀß ĞÅÑÏÓÁËÈÊÀ');
insert into reg  (id, name) values  ('97', '×ÓÂÀØÑÊÀß ĞÅÑÏÓÁËÈÊÀ');
insert into reg  (id, name) values  ('98', 'ĞÅÑÏÓÁËÈÊÀ ÑÀÕÀ(ßÊÓÒÈß)');
insert into reg  (id, name) values  ('99', 'ÅÂĞÅÉÑÊÀß ÀÎ');
insert into reg  (id, name) values  ('35', 'ĞÅÑÏÓÁËÈÊÀ ÊĞÛÌ');
insert into reg  (id, name) values  ('67', 'Ã ÑÅÂÀÑÒÎÏÎËÜ');