insert into pzn  (id, abbreviation, name) values  ('00', 'ГУ/О', 'Главное управление/Отделение (НБ)');
insert into pzn  (id, abbreviation, name) values  ('10', 'РКЦ', 'Расчетно-кассовый центр');
insert into pzn  (id, abbreviation, name) values  ('20', 'Б', 'Банк');
insert into pzn  (id, abbreviation, name) values  ('21', 'КБ', 'Коммерческий банк');
insert into pzn  (id, abbreviation, name) values  ('22', 'СБ', 'Сбербанк России');
insert into pzn  (id, abbreviation, name) values  ('23', 'АКБ', 'Акционерный коммерческий банк');
insert into pzn  (id, abbreviation, name) values  ('24', 'ЧКБ', 'Частный коммерческий банк');
insert into pzn  (id, abbreviation, name) values  ('25', 'КОПБ', 'Кооперативный банк');
insert into pzn  (id, abbreviation, name) values  ('26', 'АПБ', 'АКБ \"АгроПромБанк\" и его регион.филиалы');
insert into pzn  (id, abbreviation, name) values  ('30', 'ФБ', 'Филиал банка');
insert into pzn  (id, abbreviation, name) values  ('31', 'ФКБ', 'Филиал коммерческого банка');
insert into pzn  (id, abbreviation, name) values  ('32', 'ФСБ', 'Филиал Сбербанка');
insert into pzn  (id, abbreviation, name) values  ('33', 'ФАКБ', 'Филиал акционерного коммерческого банка');
insert into pzn  (id, abbreviation, name) values  ('34', 'ФЧКБ', 'Филиал частного коммерческого банка');
insert into pzn  (id, abbreviation, name) values  ('35', 'ФКОБ', 'Филиал кооперативного банка');
insert into pzn  (id, abbreviation, name) values  ('36', 'Отд.', 'Отделение \"АгроПромБанка\"');
insert into pzn  (id, abbreviation, name) values  ('40', 'ПУ', 'Полевое учреждение Банка России');
insert into pzn  (id, abbreviation, name) values  ('50', 'МРХ', 'Межрегиональное хранилище');
insert into pzn  (id, abbreviation, name) values  ('70', 'НКО', 'НКО (расчетные,орг-ции инкассации и др.)');
insert into pzn  (id, abbreviation, name) values  ('71', 'КЛ', 'Клиринговое учреждение');
insert into pzn  (id, abbreviation, name) values  ('72', 'ОРЦБ', 'Расчетный центр ОРЦБ');
insert into pzn  (id, abbreviation, name) values  ('98', 'ИСКЛ', 'Начат процесс ликвидации');
insert into pzn  (id, abbreviation, name) values  ('99', 'ОТЗВ', 'Огр.расх.опер. по приказу об отз.лиценз.');
insert into pzn  (id, abbreviation, name) values  ('', '', 'Признак типа не определен');
insert into pzn  (id, abbreviation, name) values  ('**', '', 'Подр. Банка России,не обслужив. клиентов');
insert into pzn  (id, abbreviation, name) values  ('90', 'ЛИКВ', 'Ликвидационная комиссия (ликвидатор)');
insert into pzn  (id, abbreviation, name) values  ('37', 'ТУСБ', 'Территориальные управления Сбербанка');
insert into pzn  (id, abbreviation, name) values  ('73', 'НДКО', 'НКО, осущ. депозитно-кредитные операции');
insert into pzn  (id, abbreviation, name) values  ('74', 'ФНКО', 'Филиал НКО');
insert into pzn  (id, abbreviation, name) values  ('91', 'КУПР', 'Конкурсный управляющий');
insert into pzn  (id, abbreviation, name) values  ('75', 'ФДКО', 'Филиал НДКО');
insert into pzn  (id, abbreviation, name) values  ('76', 'ФРП', 'Филиал расчетного центра ОРЦБ');
insert into pzn  (id, abbreviation, name) values  ('80', 'ОНК', 'Организация, не являющаяся кредитной');
insert into pzn  (id, abbreviation, name) values  ('11', 'ПРС', 'Подразделение расчетн. сети Банка России');
insert into pzn  (id, abbreviation, name) values  ('12', 'ОНБ', 'Отделение (НБ), не ведущее баланс');


insert into uer  (id, name) values  ('0', 'НЕ УЧАСТВУЕТ');
insert into uer  (id, name) values  ('1', 'ТОЛЬКО МЕЖРЕГИОНАЛЬНЫЕ РАСЧЕТЫ');
insert into uer  (id, name) values  ('2', 'ТОЛЬКО ВНУТРИРЕГИОНАЛЬНЫЕ РАСЧЕТЫ');
insert into uer  (id, name) values  ('3', 'МЕЖРЕГИОНАЛЬНЫЕ И ВНУТРИРЕГИОНАЛЬНЫЕ РАСЧЕТЫ');
insert into uer  (id, name) values  ('7', 'ИСКЛЮЧЕН ИЗ МЭР, НО РАБОТАЕТ ПО ПОДТВЕРЖДЕНИЯМ МЭР, УЧАСТНИК ВЭР');
insert into uer  (id, name) values  ('4', 'УЧАСТНИК МЭР, ВЭР И ОСОБЫЙ УЧАСТНИК РАСЧЕТОВ СИСТЕМЫ БЭСП');
insert into uer  (id, name) values  ('5', 'АССОЦИИРОВАННЫЙ УЧАСТНИК БЭСП И УЧАСТНИК ВЭР');
insert into uer  (id, name) values  ('6', 'АССОЦИИРОВАННЫЙ УЧАСТНИК БЭСП И НЕ УЧАСТНИК ВЭР');


insert into tnp  (id, name, short_name) values  ('1', 'ГОРОД', 'Г');
insert into tnp  (id, name, short_name) values  ('2', 'ПОСЕЛОК', 'П');
insert into tnp  (id, name, short_name) values  ('3', 'СЕЛО', 'С');
insert into tnp  (id, name, short_name) values  ('4', 'ПОСЕЛОК ГОРОДСКОГО ТИПА', 'ПГТ');
insert into tnp  (id, name, short_name) values  ('5', 'СТАНИЦА', 'СТ-ЦА');
insert into tnp  (id, name, short_name) values  ('6', 'АУЛ', 'АУЛ');
insert into tnp  (id, name, short_name) values  ('7', 'РАБОЧИЙ ПОСЕЛОК', 'РП');


insert into reg  (id, name) values  ('00', 'ТЕРРИТОРИЯ НЕ ОПРЕДЕЛЕНА');
insert into reg  (id, name) values  ('01', 'АЛТАЙСКИЙ КРАЙ');
insert into reg  (id, name) values  ('03', 'КРАСНОДАРСКИЙ КРАЙ');
insert into reg  (id, name) values  ('04', 'КРАСНОЯРСКИЙ КРАЙ');
insert into reg  (id, name) values  ('05', 'ПРИМОРСКИЙ КРАЙ');
insert into reg  (id, name) values  ('07', 'СТАВРОПОЛЬСКИЙ КРАЙ');
insert into reg  (id, name) values  ('08', 'ХАБАРОВСКИЙ КРАЙ');
insert into reg  (id, name) values  ('10', 'АМУРСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('11', 'АРХАНГЕЛЬСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('12', 'АСТРАХАНСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('14', 'БЕЛГОРОДСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('15', 'БРЯНСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('17', 'ВЛАДИМИРСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('18', 'ВОЛГОГРАДСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('19', 'ВОЛОГОДСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('20', 'ВОРОНЕЖСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('22', 'НИЖЕГОРОДСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('24', 'ИВАНОВСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('25', 'ИРКУТСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('26', 'РЕСПУБЛИКА ИНГУШЕТИЯ');
insert into reg  (id, name) values  ('27', 'КАЛИНИНГРАДСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('28', 'ТВЕРСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('29', 'КАЛУЖСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('30', 'КАМЧАТСКИЙ КРАЙ');
insert into reg  (id, name) values  ('32', 'КЕМЕРОВСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('33', 'КИРОВСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('34', 'КОСТРОМСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('36', 'САМАРСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('37', 'КУРГАНСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('38', 'КУРСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('40', 'Г САНКТ-ПЕТЕРБУРГ');
insert into reg  (id, name) values  ('41', 'ЛЕНИНГРАДСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('42', 'ЛИПЕЦКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('44', 'МАГАДАНСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('45', 'Г МОСКВА');
insert into reg  (id, name) values  ('46', 'МОСКОВСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('47', 'МУРМАНСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('49', 'НОВГОРОДСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('50', 'НОВОСИБИРСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('52', 'ОМСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('53', 'ОРЕНБУРГСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('54', 'ОРЛОВСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('56', 'ПЕНЗЕНСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('57', 'ПЕРМСКИЙ КРАЙ');
insert into reg  (id, name) values  ('58', 'ПСКОВСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('60', 'РОСТОВСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('61', 'РЯЗАНСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('63', 'САРАТОВСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('64', 'САХАЛИНСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('65', 'СВЕРДЛОВСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('66', 'СМОЛЕНСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('68', 'ТАМБОВСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('69', 'ТОМСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('70', 'ТУЛЬСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('71', 'ТЮМЕНСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('73', 'УЛЬЯНОВСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('75', 'ЧЕЛЯБИНСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('76', 'ЗАБАЙКАЛЬСКИЙ КРАЙ');
insert into reg  (id, name) values  ('77', 'ЧУКОТСКИЙ АО');
insert into reg  (id, name) values  ('78', 'ЯРОСЛАВСКАЯ ОБЛАСТЬ');
insert into reg  (id, name) values  ('79', 'РЕСПУБЛИКА АДЫГЕЯ');
insert into reg  (id, name) values  ('80', 'РЕСПУБЛИКА БАШКОРТОСТАН');
insert into reg  (id, name) values  ('81', 'РЕСПУБЛИКА БУРЯТИЯ');
insert into reg  (id, name) values  ('82', 'РЕСПУБЛИКА ДАГЕСТАН');
insert into reg  (id, name) values  ('83', 'КАБАРДИНО-БАЛКАРСКАЯ РЕСПУБЛИКА');
insert into reg  (id, name) values  ('84', 'РЕСПУБЛИКА АЛТАЙ');
insert into reg  (id, name) values  ('85', 'РЕСПУБЛИКА КАЛМЫКИЯ');
insert into reg  (id, name) values  ('86', 'РЕСПУБЛИКА КАРЕЛИЯ');
insert into reg  (id, name) values  ('87', 'РЕСПУБЛИКА КОМИ');
insert into reg  (id, name) values  ('88', 'РЕСПУБЛИКА МАРИЙ ЭЛ');
insert into reg  (id, name) values  ('89', 'РЕСПУБЛИКА МОРДОВИЯ');
insert into reg  (id, name) values  ('90', 'РЕСПУБЛИКА СЕВЕРНАЯ ОСЕТИЯ-АЛАНИЯ');
insert into reg  (id, name) values  ('91', 'КАРАЧАЕВО-ЧЕРКЕССКАЯ РЕСПУБЛИКА');
insert into reg  (id, name) values  ('92', 'РЕСПУБЛИКА ТАТАРСТАН');
insert into reg  (id, name) values  ('93', 'РЕСПУБЛИКА ТЫВА');
insert into reg  (id, name) values  ('94', 'УДМУРТСКАЯ РЕСПУБЛИКА');
insert into reg  (id, name) values  ('95', 'РЕСПУБЛИКА ХАКАСИЯ');
insert into reg  (id, name) values  ('96', 'ЧЕЧЕНСКАЯ РЕСПУБЛИКА');
insert into reg  (id, name) values  ('97', 'ЧУВАШСКАЯ РЕСПУБЛИКА');
insert into reg  (id, name) values  ('98', 'РЕСПУБЛИКА САХА(ЯКУТИЯ)');
insert into reg  (id, name) values  ('99', 'ЕВРЕЙСКАЯ АО');
insert into reg  (id, name) values  ('35', 'РЕСПУБЛИКА КРЫМ');
insert into reg  (id, name) values  ('67', 'Г СЕВАСТОПОЛЬ');